### ISSUE TITLE
Version of python-redis needs to be upgraded for openvas

### ISSUE THREAD

**Issue by damonmaria** [admirito/gvm-containers#6]
```
openvas_1         | 2020-02-12 23:15:12,950 OSPD - openvas: ERROR: (ospd.ospd) While scanning 101.98.66.45:
openvas_1         | Traceback (most recent call last):
openvas_1         |   File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 777, in parallel_scan
openvas_1         |     ret = self.exec_scan(scan_id, target)
openvas_1         |   File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 1439, in exec_scan
openvas_1         |     self.openvas_db.remove_list_item('internal/dbindex', i)
openvas_1         |   File "/usr/lib/python3/dist-packages/ospd_openvas/db.py", line 291, in remove_list_item
openvas_1         |     ctx.lrem(key, count=LIST_ALL, value=value)
openvas_1         | TypeError: lrem() got an unexpected keyword argument 'count'
```

Here's the relevant issue: https://github.com/greenbone/ospd-openvas/issues/179

**Comment by konvergence** [comment]
Hi,

This is because the installed package python3-redis is 2.10.6

I check the availables packages into the docker image 
if you add the upgrade instruction into your Dockerfile it solve the issue

```
root@4dded529a642:/# apt-get update

root@4dded529a642:/# apt-cache madison python3-redis
python3-redis |   3.3.11-2 | http://ppa.launchpad.net/mrazavi/gvm/ubuntu bionic/main amd64 Packages
python3-redis | 2.10.6-2ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

root@4dded529a642:/# apt-get --only-upgrade install python3-redis
```


Please advise

**Comment by mrod23** [comment]
@konvergence  I'm getting this issue also. Which Dockerfile did you update?

**Comment by konvergence** [comment]
@mrod23 , I have proposed a pull request :  https://github.com/admirito/gvm-containers/pull/10

**Comment by admirito** [comment]
The new version is based on ubuntu:focal and I think the issue is solved. If you think the problem persist please reopen the issue.
